// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbHsr0BeFrBLLyldhRgHBQNAqlf8a8gkQ',
    appId: '1:379057544523:web:9d3f9901c82e4327235cce',
    messagingSenderId: '379057544523',
    projectId: 'engademy',
    authDomain: 'engademy.firebaseapp.com',
    storageBucket: 'engademy.firebasestorage.app',
    measurementId: 'G-WN9GY9QPSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq995duZ-FIShJ0wMm6-zljVxs5cDk6vs',
    appId: '1:379057544523:android:35ebb263959df48d235cce',
    messagingSenderId: '379057544523',
    projectId: 'engademy',
    storageBucket: 'engademy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrWi-TvNsiD_3tIcwRNyjNIYt2kZglIM4',
    appId: '1:379057544523:ios:5753d356faaed795235cce',
    messagingSenderId: '379057544523',
    projectId: 'engademy',
    storageBucket: 'engademy.firebasestorage.app',
    iosClientId: '379057544523-8k84i0sviu4cm0q5b4a79idp09b29f8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.engademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrWi-TvNsiD_3tIcwRNyjNIYt2kZglIM4',
    appId: '1:379057544523:ios:5753d356faaed795235cce',
    messagingSenderId: '379057544523',
    projectId: 'engademy',
    storageBucket: 'engademy.firebasestorage.app',
    iosClientId: '379057544523-8k84i0sviu4cm0q5b4a79idp09b29f8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.engademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbHsr0BeFrBLLyldhRgHBQNAqlf8a8gkQ',
    appId: '1:379057544523:web:8e0b18aac7082fb6235cce',
    messagingSenderId: '379057544523',
    projectId: 'engademy',
    authDomain: 'engademy.firebaseapp.com',
    storageBucket: 'engademy.firebasestorage.app',
    measurementId: 'G-GJVR8RVE15',
  );
}
